In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("nba_games.csv", index_col=0)

In [15]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,22.8,29.0,178.0,111.0,DAL,95,1,2016,2015-12-09,True
1,240.0,240.0,36.0,100.0,0.360,7.0,31.0,0.226,16.0,19.0,...,50.0,32.6,152.0,111.0,ATL,98,0,2016,2015-12-09,False
2,240.0,240.0,37.0,85.0,0.435,8.0,19.0,0.421,17.0,23.0,...,20.0,30.9,148.0,116.0,SAS,107,1,2018,2017-10-18,False
3,240.0,240.0,41.0,89.0,0.461,8.0,21.0,0.381,17.0,19.0,...,28.6,30.9,138.0,118.0,MIN,99,0,2018,2017-10-18,True
4,240.0,240.0,27.0,86.0,0.314,6.0,26.0,0.231,15.0,20.0,...,16.8,30.9,157.0,90.0,MEM,92,1,2021,2021-04-30,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,240.0,35.0,81.0,0.432,11.0,26.0,0.423,27.0,36.0,...,34.2,33.7,160.0,118.0,OKC,92,0,2019,2018-10-19,True
17768,240.0,240.0,37.0,74.0,0.500,13.0,25.0,0.520,26.0,37.0,...,25.0,30.0,139.0,129.0,ORL,108,1,2017,2016-12-14,True
17769,240.0,240.0,42.0,89.0,0.472,14.0,33.0,0.424,10.0,20.0,...,25.6,29.9,175.0,126.0,LAC,113,0,2017,2016-12-14,False
17770,240.0,240.0,41.0,85.0,0.482,9.0,26.0,0.346,26.0,30.0,...,27.7,27.1,150.0,126.0,MIA,106,1,2020,2020-09-19,True
17771,240.0,240.0,33.0,85.0,0.388,12.0,44.0,0.273,28.0,34.0,...,51.5,36.2,141.0,114.0,BOS,117,0,2020,2020-09-19,False

In [16]:
df = df.sort_values("date")

In [17]:
df = df.reset_index(drop=True)

In [18]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
1,240.0,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
2,240.0,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
3,240.0,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True
4,240.0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,...,42.9,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False
17768,240.0,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,...,45.0,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True
17769,240.0,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,...,33.3,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False
17770,240.0,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,...,33.3,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False
17771,240.0,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,...,100.0,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True

In [19]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [20]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
1,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
2,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True
4,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,0.737,...,42.9,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,45.0,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,33.3,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,33.3,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,100.0,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True

In [21]:
def add_target(team):
    newteam = team.copy()
    newteam["target"] = newteam["won"].shift(-1)
    return newteam
df = df.groupby("team", group_keys=False).apply(add_target)

In [22]:
df[df["team"] == "WAS"]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
11,240.0,33.0,84.0,0.393,7.0,28.0,0.250,15.0,25.0,0.600,...,25.2,134.0,98.0,ORL,87,1,2016,2015-10-28,True,True
63,240.0,35.0,68.0,0.515,12.0,21.0,0.571,36.0,44.0,0.818,...,32.4,138.0,122.0,MIL,113,1,2016,2015-10-30,True,False
69,240.0,38.0,90.0,0.422,6.0,22.0,0.273,28.0,33.0,0.848,...,28.7,153.0,108.0,NYK,117,0,2016,2015-10-31,False,True
124,240.0,42.0,87.0,0.483,8.0,23.0,0.348,10.0,14.0,0.714,...,30.0,160.0,109.0,SAS,99,0,2016,2015-11-04,True,False
161,240.0,36.0,88.0,0.409,8.0,25.0,0.320,18.0,23.0,0.783,...,41.6,146.0,103.0,BOS,118,1,2016,2015-11-06,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17471,240.0,38.0,82.0,0.463,8.0,21.0,0.381,18.0,20.0,0.900,...,34.4,245.0,116.0,BOS,144,1,2022,2022-04-03,False,True
17483,240.0,56.0,101.0,0.554,13.0,30.0,0.433,7.0,14.0,0.500,...,32.8,168.0,132.0,MIN,114,1,2022,2022-04-05,True,False
17510,240.0,42.0,86.0,0.488,10.0,35.0,0.286,9.0,11.0,0.818,...,60.2,159.0,114.0,ATL,118,1,2022,2022-04-06,False,False
17538,240.0,35.0,69.0,0.507,9.0,28.0,0.321,13.0,17.0,0.765,...,35.5,135.0,104.0,NYK,114,0,2022,2022-04-08,False,False
17558,240.0,42.0,94.0,0.447,8.0,23.0,0.348,16.0,26.0,0.615,...,37.3,161.0,118.0,CHO,124,1,2022,2022-04-10,False,NaN

In [23]:
df["team"]

0        NOP
1        CLE
2        CHI
3        GSW
4        ATL
        ...
17767    BOS
17768    GSW
17769    BOS
17770    BOS
17771    GSW
Name: team, Length: 17772, dtype: object

In [24]:
df["target"][pd.isnull(df["target"])] = 2

/var/folders/t0/4lvwqtnn3371qr_st_58d9tc0000gn/T/ipykernel_1518/1618397414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [25]:
df["target"] = df["target"].astype(int, errors="ignore")

In [26]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
1,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
2,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True,1
4,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,0.737,...,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False,0
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True,1
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False,0
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False,2
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True,2

In [27]:
df["won"].value_counts()

won
False    8886
True     8886
Name: count, dtype: int64

In [28]:
df["target"].value_counts()

target
1    8872
0    8870
2      30
Name: count, dtype: int64

In [29]:
nulls = pd.isnull(df)

In [30]:
nulls = nulls.sum()

In [31]:
nulls = nulls[nulls > 0]

In [32]:
nulls

+/-             17772
mp_max          17772
mp_max.1        17772
+/-_opp         17772
mp_max_opp      17772
mp_max_opp.1    17772
dtype: int64

In [33]:
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [34]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=142)

In [35]:
df = df[valid_columns].copy()

In [36]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
1,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
2,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True,1
4,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,0.737,...,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False,0
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True,1
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False,0
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False,2
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True,2

In [37]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /opt/homebrew/lib/python3.11/site-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /opt/homebrew/lib/python3.11/site-packages (from scikit-learn) (1.24.3)
Requirement already satisfied: scipy>=1.3.2 in /opt/homebrew/lib/python3.11/site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /opt/homebrew/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/homebrew/lib/python3.11/site-packages (from scikit-learn) (3.1.0)
Note: you may need to restart the kernel to use updated packages.

In [38]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)
sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split)

In [39]:
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]

In [40]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [41]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [42]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.363636,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.277279,0.554502,0.317647,GSW,0.451923,1.0,2016,2015-10-27,False,0
1,0.0,0.431818,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.160462,0.345972,0.317647,CHI,0.317308,1.0,2016,2015-10-27,False,1
2,0.0,0.409091,0.397059,0.373206,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.088575,0.232227,0.329412,CLE,0.298077,0.0,2016,2015-10-27,True,1
3,0.0,0.500000,0.529412,0.377990,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.215661,0.530806,0.505882,NOP,0.298077,0.0,2016,2015-10-27,True,1
4,0.0,0.409091,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.019255,0.203791,0.317647,DET,0.403846,0.0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.182285,0.208531,0.411765,GSW,0.413462,0.0,2022,2022-06-10,False,0
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.928113,1.000000,0.411765,BOS,0.288462,0.0,2022,2022-06-13,True,1
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.181001,0.630332,0.352941,GSW,0.384615,1.0,2022,2022-06-13,False,0
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.120668,0.459716,0.400000,GSW,0.375000,0.0,2022,2022-06-16,False,2
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.263158,0.246445,0.576471,BOS,0.250000,1.0,2022,2022-06-16,True,2

In [43]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [44]:
predictors = list(selected_columns[sfs.get_support()])

In [45]:
predictors

['mp',
 'fg%',
 '3p%',
 'orb',
 'ts%',
 'usg%',
 '3p%_max',
 'ft_max',
 'fta_max',
 '+/-_max',
 'drb%_max',
 'trb%_max',
 'tov%_max',
 'usg%_max',
 'mp_opp',
 'fg_opp',
 '3p_opp',
 'ft%_opp',
 'blk_opp',
 'usg%_opp',
 'fga_max_opp',
 '3p_max_opp',
 'ft_max_opp',
 'ft%_max_opp',
 'blk_max_opp',
 'pf_max_opp',
 'pts_max_opp',
 'drb%_max_opp',
 'blk%_max_opp',
 'usg%_max_opp']

In [46]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []
    seasons = sorted(data["season"].unique())
    for i in range(start, len(seasons), step):
        season = seasons[i]
        train = data[data["season"] < season]
        test = data[data["season"] == season]
        model.fit(train[predictors], train["target"])
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)
        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual", "prediction"]
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [47]:
predictions = backtest(df, rr, predictors)

In [48]:
predictions

       actual  prediction
5250        1           1
5251        1           1
5252        0           0
5253        1           0
5254        0           1
...       ...         ...
17767       0           0
17768       1           1
17769       0           1
17770       2           1
17771       2           1

[12522 rows x 2 columns]

In [49]:
from sklearn.metrics import accuracy_score
predictions = predictions[predictions["actual"] != 2]
accuracy_score(predictions["actual"], predictions["prediction"])

0.5485110470701249

In [50]:
df.groupby("home").apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

home
0.0    0.428314
1.0    0.571686
dtype: float64

In [81]:
def find_team_averages(team):
    removed_cols = ["team", "season"]
    selected_columns = team.columns[~team.columns.isin(removed_cols)]
    team = team[selected_columns]
    rolling = team.rolling(10).mean()
    return rolling

In [82]:
df_rolling = df[list(selected_columns) + ["won","team", "season"]]

In [83]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,team,season
0,0.0,0.363636,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.079,0.679245,0.277279,0.554502,0.317647,0.451923,1.0,False,NOP,2016
1,0.0,0.431818,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.140,0.509434,0.160462,0.345972,0.317647,0.317308,1.0,False,CLE,2016
2,0.0,0.409091,0.397059,0.373206,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.185,0.270440,0.088575,0.232227,0.329412,0.298077,0.0,True,CHI,2016
3,0.0,0.500000,0.529412,0.377990,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.063,0.344864,0.215661,0.530806,0.505882,0.298077,0.0,True,GSW,2016
4,0.0,0.409091,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.047,0.300839,0.019255,0.203791,0.317647,0.403846,0.0,False,ATL,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.103,0.401468,0.182285,0.208531,0.411765,0.413462,0.0,False,BOS,2022
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.124,0.423480,0.928113,1.000000,0.411765,0.288462,0.0,True,GSW,2022
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.076,0.300839,0.181001,0.630332,0.352941,0.384615,1.0,False,BOS,2022
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.063,0.300839,0.120668,0.459716,0.400000,0.375000,0.0,False,BOS,2022
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.160,1.000000,0.263158,0.246445,0.576471,0.250000,1.0,True,GSW,2022

In [84]:
df_rolling["team"]

0        NOP
1        CLE
2        CHI
3        GSW
4        ATL
        ...
17767    BOS
17768    GSW
17769    BOS
17770    BOS
17771    GSW
Name: team, Length: 17772, dtype: object

In [85]:
df_rolling["season"]

0        2016
1        2016
2        2016
3        2016
4        2016
         ...
17767    2022
17768    2022
17769    2022
17770    2022
17771    2022
Name: season, Length: 17772, dtype: int64

In [86]:
print(df_rolling.dtypes)

mp           float64
fg           float64
fga          float64
fg%          float64
3p           float64
              ...
total_opp    float64
home_opp     float64
won             bool
team          object
season         int64
Length: 139, dtype: object

In [87]:
df_rolling = df_rolling.groupby(["team", "season"], as_index=False).apply(find_team_averages).reset_index(level=[0, 1], drop=True).reset_index()

In [88]:
df_rolling

,index,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,17767,0.0,0.495455,0.369118,0.500957,0.386207,0.403030,0.434204,0.386047,0.322222,...,0.359748,0.0535,0.0605,0.346541,0.165340,0.391469,0.504706,0.465385,0.5,0.5
17768,17768,0.0,0.545455,0.401471,0.530622,0.386207,0.396970,0.440261,0.365116,0.311111,...,0.393463,0.0472,0.0571,0.316143,0.167394,0.395261,0.532941,0.478846,0.5,0.6
17769,17769,0.0,0.540909,0.402941,0.523445,0.375862,0.403030,0.424466,0.325581,0.279365,...,0.408945,0.0531,0.0582,0.303669,0.193196,0.399052,0.507059,0.477885,0.6,0.5
17770,17770,0.0,0.540909,0.379412,0.546172,0.386207,0.401515,0.438005,0.306977,0.268254,...,0.411812,0.0783,0.0583,0.251258,0.203466,0.380095,0.498824,0.476923,0.5,0.5
17771,17771,0.0,0.538636,0.382353,0.541388,0.375862,0.378788,0.445012,0.332558,0.295238,...,0.400917,0.0786,0.1074,0.330398,0.206804,0.373934,0.507059,0.486538,0.5,0.5

In [89]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols
df = pd.concat([df, df_rolling], axis=1)

In [90]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,ast%_max_opp_10,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10
0,0.0,0.363636,0.338235,0.366029,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.431818,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.409091,0.397059,0.373206,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.500000,0.529412,0.377990,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.409091,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.359748,0.0535,0.0605,0.346541,0.165340,0.391469,0.504706,0.465385,0.5,0.5
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.393463,0.0472,0.0571,0.316143,0.167394,0.395261,0.532941,0.478846,0.5,0.6
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.408945,0.0531,0.0582,0.303669,0.193196,0.399052,0.507059,0.477885,0.6,0.5
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.411812,0.0783,0.0583,0.251258,0.203466,0.380095,0.498824,0.476923,0.5,0.5
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.400917,0.0786,0.1074,0.330398,0.206804,0.373934,0.507059,0.486538,0.5,0.5

In [91]:
df = df.dropna()

In [92]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,ast%_max_opp_10,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10
9,0.0,0.522727,0.294118,0.612440,0.206897,0.227273,0.375297,0.465116,0.476190,0.623104,...,0.311927,0.0628,0.0679,0.413522,0.124134,0.361611,0.449412,0.347115,0.4,0.8
10,0.0,0.409091,0.588235,0.241627,0.172414,0.333333,0.228029,0.162791,0.174603,0.611435,...,0.323853,0.0649,0.0735,0.409119,0.134531,0.363507,0.452941,0.347115,0.5,0.8
11,0.0,0.318182,0.352941,0.296651,0.241379,0.363636,0.296912,0.325581,0.380952,0.533256,...,0.321560,0.0632,0.0842,0.421593,0.133504,0.345498,0.454118,0.343269,0.4,0.7
12,0.0,0.386364,0.455882,0.303828,0.379310,0.439394,0.395487,0.232558,0.269841,0.546091,...,0.315252,0.0658,0.0820,0.449476,0.153787,0.346919,0.458824,0.339423,0.5,0.6
13,0.0,0.363636,0.441176,0.287081,0.310345,0.454545,0.314727,0.720930,0.539683,0.899650,...,0.328899,0.0660,0.0782,0.531761,0.161746,0.272512,0.457647,0.344231,0.4,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.359748,0.0535,0.0605,0.346541,0.165340,0.391469,0.504706,0.465385,0.5,0.5
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.393463,0.0472,0.0571,0.316143,0.167394,0.395261,0.532941,0.478846,0.5,0.6
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.408945,0.0531,0.0582,0.303669,0.193196,0.399052,0.507059,0.477885,0.6,0.5
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.411812,0.0783,0.0583,0.251258,0.203466,0.380095,0.498824,0.476923,0.5,0.5
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.400917,0.0786,0.1074,0.330398,0.206804,0.373934,0.507059,0.486538,0.5,0.5

In [95]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col
def add_col(df, col_name):
    return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))
df["home_next"] = add_col(df, "home")
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

/var/folders/t0/4lvwqtnn3371qr_st_58d9tc0000gn/T/ipykernel_1518/1846749287.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["home_next"] = add_col(df, "home")
/var/folders/t0/4lvwqtnn3371qr_st_58d9tc0000gn/T/ipykernel_1518/1846749287.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["team_opp_next"] = add_col(df, "team_opp")
/var/folders/t0/4lvwqtnn3371qr_st_58d9tc0000gn/T/ipykernel_1518/1846749287.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["team_opp_next"] = add_col(df, "team_opp")
/var/folders/t0/4lvwqtnn3371qr_st_58d9tc0000gn/T/ipykernel_1518/1846749287.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["date_next"] = add_col(df, "date")
/var/folders/t0/4lvwqtnn3371qr_st_58d9tc0000gn/T/ipykernel_1518/1846749287.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_next"] = add_col(df, "date")

In [96]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,home_next,team_opp_next,date_next
9,0.0,0.522727,0.294118,0.612440,0.206897,0.227273,0.375297,0.465116,0.476190,0.623104,...,0.413522,0.124134,0.361611,0.449412,0.347115,0.4,0.8,1.0,DAL,2015-10-29
10,0.0,0.409091,0.588235,0.241627,0.172414,0.333333,0.228029,0.162791,0.174603,0.611435,...,0.409119,0.134531,0.363507,0.452941,0.347115,0.5,0.8,1.0,OKC,2015-10-30
11,0.0,0.318182,0.352941,0.296651,0.241379,0.363636,0.296912,0.325581,0.380952,0.533256,...,0.421593,0.133504,0.345498,0.454118,0.343269,0.4,0.7,0.0,MIL,2015-10-30
12,0.0,0.386364,0.455882,0.303828,0.379310,0.439394,0.395487,0.232558,0.269841,0.546091,...,0.449476,0.153787,0.346919,0.458824,0.339423,0.5,0.6,1.0,GSW,2015-10-31
13,0.0,0.363636,0.441176,0.287081,0.310345,0.454545,0.314727,0.720930,0.539683,0.899650,...,0.531761,0.161746,0.272512,0.457647,0.344231,0.4,0.6,0.0,SAC,2015-10-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.346541,0.165340,0.391469,0.504706,0.465385,0.5,0.5,0.0,GSW,2022-06-13
17768,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.316143,0.167394,0.395261,0.532941,0.478846,0.5,0.6,0.0,BOS,2022-06-16
17769,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.303669,0.193196,0.399052,0.507059,0.477885,0.6,0.5,1.0,GSW,2022-06-16
17770,0.0,0.340909,0.294118,0.373206,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.251258,0.203466,0.380095,0.498824,0.476923,0.5,0.5,NaN,None,None
17771,0.0,0.431818,0.470588,0.344498,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.330398,0.206804,0.373934,0.507059,0.486538,0.5,0.5,NaN,None,None

In [97]:
df = df.copy()

In [100]:
full = df.merge(
    df[rolling_cols + ["team_opp_next", "date_next", "team"]], 
    left_on = ["team", "date_next"],
    right_on=["team_opp_next", "date_next"]
)

In [101]:
full

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,blk%_max_opp_10_y,tov%_max_opp_10_y,usg%_max_opp_10_y,ortg_max_opp_10_y,drtg_max_opp_10_y,total_opp_10_y,home_opp_10_y,won_10_y,team_opp_next_y,team_y
0,0.0,0.522727,0.294118,0.612440,0.206897,0.227273,0.375297,0.465116,0.476190,0.623104,...,0.0759,0.360587,0.136585,0.450711,0.409412,0.339423,0.5,0.5,LAC,DAL
1,0.0,0.409091,0.588235,0.241627,0.172414,0.333333,0.228029,0.162791,0.174603,0.611435,...,0.0994,0.439623,0.164056,0.414692,0.438824,0.340385,0.5,0.4,ORL,OKC
2,0.0,0.318182,0.352941,0.296651,0.241379,0.363636,0.296912,0.325581,0.380952,0.533256,...,0.0812,0.472642,0.159050,0.366825,0.472941,0.370192,0.4,0.5,WAS,MIL
3,0.0,0.386364,0.455882,0.303828,0.379310,0.439394,0.395487,0.232558,0.269841,0.546091,...,0.0727,0.405451,0.122208,0.443602,0.431765,0.325962,0.6,0.5,NOP,GSW
4,0.0,0.250000,0.382353,0.191388,0.310345,0.212121,0.593824,0.627907,0.476190,0.886814,...,0.0842,0.421593,0.133504,0.345498,0.454118,0.343269,0.4,0.7,MIL,WAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15139,0.0,0.545455,0.426471,0.511962,0.448276,0.469697,0.440618,0.372093,0.365079,0.659277,...,0.0546,0.428826,0.207831,0.419431,0.478824,0.487500,0.6,0.3,BOS,GSW
15140,0.0,0.477273,0.455882,0.409091,0.517241,0.590909,0.414489,0.255814,0.222222,0.766628,...,0.0605,0.346541,0.165340,0.391469,0.504706,0.465385,0.5,0.5,GSW,BOS
15141,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.0549,0.346541,0.212323,0.385782,0.510588,0.449038,0.4,0.5,BOS,GSW
15142,0.0,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.0582,0.303669,0.193196,0.399052,0.507059,0.477885,0.6,0.5,GSW,BOS
15143,0.0,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.0571,0.316143,0.167394,0.395261,0.532941,0.478846,0.5,0.6,BOS,GSW

In [103]:
full[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

      team_x team_opp_next_x team_y team_opp_next_y   date_next
0        LAC             DAL    DAL             LAC  2015-10-29
1        ORL             OKC    OKC             ORL  2015-10-30
2        WAS             MIL    MIL             WAS  2015-10-30
3        NOP             GSW    GSW             NOP  2015-10-31
4        MIL             WAS    WAS             MIL  2015-10-30
...      ...             ...    ...             ...         ...
15139    BOS             GSW    GSW             BOS  2022-06-10
15140    GSW             BOS    BOS             GSW  2022-06-13
15141    BOS             GSW    GSW             BOS  2022-06-13
15142    GSW             BOS    BOS             GSW  2022-06-16
15143    BOS             GSW    GSW             BOS  2022-06-16

[15144 rows x 5 columns]

In [104]:
removed_columns = list(full.columns[full.dtypes == "object"]) + removed_columns

In [105]:
removed_columns

['team_x',
 'team_opp',
 'date',
 'team_opp_next_x',
 'date_next',
 'team_opp_next_y',
 'team_y',
 'season',
 'date',
 'won',
 'target',
 'team',
 'team_opp']

In [106]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]

In [107]:
sfs.fit(full[selected_columns], full["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [109]:
predictors = list(selected_columns[sfs.get_support()])

In [110]:
predictors

['ft%',
 'usg%',
 '+/-_max',
 'efg%_max',
 '3p_opp',
 'usg%_opp',
 'stl_max_opp',
 'usg%_max_opp',
 'mp_10_x',
 'blk%_10_x',
 'usg%_10_x',
 'pts_max_10_x',
 'ast%_max_10_x',
 'tov%_max_10_x',
 'mp_opp_10_x',
 'ft%_opp_10_x',
 'tov_opp_10_x',
 'usg%_opp_10_x',
 'stl%_max_opp_10_x',
 'home_next',
 'usg%_10_y',
 'fga_max_10_y',
 'fg%_max_10_y',
 '3p%_max_10_y',
 'ast%_max_10_y',
 'ast%_opp_10_y',
 'blk%_opp_10_y',
 'usg%_opp_10_y',
 'ts%_max_opp_10_y',
 'ftr_max_opp_10_y']

In [111]:
predictions = backtest(full, rr, predictors)

In [114]:
accuracy_score(predictions["actual"], predictions["prediction"])

0.5591760299625468